gamma = '5e11';
dt = 10;
sweeps = 20e3;
%dropLogFactor = 3;
dropLogFactor = 200;
DLdataStartIndex = 2;

loadFromCache = false;

T = 10;
%plotHairpinStateLowTempGamma(5, T, 10, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(6, T, 10, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(7, T, 10, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(8, T, 10, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(10, T, 20, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(12, T, 20, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(14, T, 20, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(17, T, 25, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(20, T, 30, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
plotHairpinStateLowTempGamma(22, T, 35, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(24, T, 40, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
plotHairpinStateLowTempGamma(26, T, 43, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(28, T, 45, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
plotHairpinStateLowTempGamma(31, T, 55, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(34, T, 60, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
plotHairpinStateLowTempGamma(37, T, 65, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(40, T, 70, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
plotHairpinStateLowTempGamma(44, T, 85, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(48, T, 100, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(57, T, 120, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(67, T, 160, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(80, T, 200, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);


T = 30;
%plotHairpinStateLowTempGamma(5, T, 15, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(6, T, 15, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);   
%plotHairpinStateLowTempGamma(7, T, 15, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(8, T, 15, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);   
%plotHairpinStateLowTempGamma(10, T, 35, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(12, T, 35, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);  
%plotHairpinStateLowTempGamma(14, T, 35, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(17, T, 40, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);  
%plotHairpinStateLowTempGamma(20, T, 50, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
plotHairpinStateLowTempGamma(22, T, 55, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(24, T, 60, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);  
plotHairpinStateLowTempGamma(26, T, 70, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(28, T, 75, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
plotHairpinStateLowTempGamma(31, T, 85, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(34, T, 100, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);  
plotHairpinStateLowTempGamma(37, T, 110, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(40, T, 120, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
plotHairpinStateLowTempGamma(44, T, 140, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(48, T, 160, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache); 
%plotHairpinStateLowTempGamma(57, T, 200, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
%plotHairpinStateLowTempGamma(67, T, 280, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache); 
%plotHairpinStateLowTempGamma(80, T, 350, sweeps, '*', gamma, dt, dropLogFactor, DLdataStartIndex, loadFromCache);
